export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  EMPRESA: 'EMPRESA',
  ASISTENTE_TECNICO: 'ASISTENTE_TECNICO',
  CAFICULTOR: 'CAFICULTOR',
};

// Opciones del menú lateral
export const MENU_OPTIONS = [
  {
    id: 'perfil_gr',
    label: 'Perfil (Genérico)',
    icon: 'user',
    path: '/dashboard/perfil',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'grid',
    path: '/dashboard',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'zonas',
    label: 'Zonas',
    icon: 'map',
    path: '/dashboard/zonas',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'extensionistas',
    label: 'Extensionistas / Agrónomos',
    icon: 'users',
    path: '/dashboard/extensionistas',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'caficultores',
    label: 'Caficultores',
    icon: 'users',
    path: '/dashboard/caficultores',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'grupo_caficultores',
    label: 'Grupo de caficultores',
    icon: 'users',
    path: '/dashboard/grupos',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'calendario',
    label: 'Calendario',
    icon: 'calendar',
    path: '/dashboard/calendario',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'sitios-web_gr',
    label: 'Sitios web (Genérico)',
    icon: 'globe',
    path: '/dashboard/sitios-web',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'mensajeria',
    label: 'Mensajería (Chat)',
    icon: 'message-square',
    path: '/dashboard/mensajeria',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'educacion_at',
    label: 'Contenido Educacional',
    icon: 'book-open',
    path: '/dashboard/educacion',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'estaciones',
    label: 'Estaciones',
    icon: 'cloud-lightning',
    path: '/dashboard/estaciones',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'fincas',
    label: 'Fincas',
    icon: 'home',
    path: '/dashboard/fincas',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'estadisticas',
    label: 'Estadísticas',
    icon: 'bar-chart-2',
    path: '/dashboard/estadisticas',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'rentabilidad',
    label: 'Rentabilidad',
    icon: 'dollar-sign',
    path: '/dashboard/rentabilidad',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'pronostico',
    label: 'Pronóstico de cosecha',
    icon: 'trending-up',
    path: '/dashboard/pronostico',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'volumen',
    label: 'Volumen de cosechado',
    icon: 'database',
    path: '/dashboard/volumen',
    roles: [ROLES.EMPRESA, ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'ubicaciones',
    label: 'Ubicaciones',
    icon: 'map-pin',
    path: '/dashboard/ubicaciones',
    roles: [ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'soporte',
    label: 'Soporte',
    icon: 'help-circle',
    path: '/dashboard/soporte',
    roles: [ROLES.ASISTENTE_TECNICO],
  },
  {
    id: 'at_chats',
    label: 'Chats',
    icon: 'message',
    path: '/dashboard/chats',
    roles: [ROLES.ASISTENTE_TECNICO],
  },

  // --- Opciones MENU SUPER ADMIN ---
  {
    id: 'sa_dashboard',
    label: 'Dashboard Global',
    icon: 'home',
    path: '/dashboard/superadmin',
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'sa_usuarios',
    label: 'Usuarios',
    icon: 'users',
    roles: [ROLES.SUPER_ADMIN],
    subItems: [
      { id: 'sa_admin_usuarios', label: 'Admin. Usuarios', path: '/dashboard/superadmin/usuarios' },
      { id: 'sa_roles', label: 'Roles', path: '/dashboard/superadmin/roles' },
      { id: 'sa_permisos', label: 'Permisos', path: '/dashboard/superadmin/permisos' },
    ]
  },
  {
    id: 'sa_empresas',
    label: 'Empresas',
    icon: 'briefcase',
    path: '/dashboard/superadmin/empresas',
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'sa_extensionistas',
    label: 'Extensionistas',
    icon: 'user-check',
    path: '/dashboard/superadmin/extensionistas',
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'sa_caficultores',
    label: 'Caficultores',
    icon: 'user',
    path: '/dashboard/superadmin/caficultores',
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'sa_suscripciones',
    label: 'Suscripciones',
    icon: 'credit-card',
    path: '/dashboard/superadmin/suscripciones',
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'sa_estaciones',
    label: 'Estaciones IoT',
    icon: 'rss',
    path: '/dashboard/superadmin/estaciones',
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'sa_analitica',
    label: 'Analítica de Datos',
    icon: 'pie-chart',
    path: '/dashboard/superadmin/analitica',
    roles: [ROLES.SUPER_ADMIN],
  },

  // --- Opciones MENU CAFICULTOR ---
  {
    id: 'caf_mi_finca',
    label: 'Mi Finca',
    icon: 'home',
    path: '/dashboard/caficultor/mi-finca',
    roles: [ROLES.CAFICULTOR],
  },
  {
    id: 'caf_chat',
    label: 'Chat y mensajería',
    icon: 'message-square',
    path: '/dashboard/caficultor/chat',
    roles: [ROLES.CAFICULTOR],
  },
  {
    id: 'caf_perfil',
    label: 'Perfil',
    icon: 'user',
    path: '/dashboard/caficultor/perfil',
    roles: [ROLES.CAFICULTOR],
  },
  {
    id: 'caf_estaciones',
    label: 'Estaciones',
    icon: 'cloud-lightning',
    path: '/dashboard/caficultor/estaciones',
    roles: [ROLES.CAFICULTOR],
  },
  {
    id: 'caf_sitios_web',
    label: 'Sitios web',
    icon: 'globe',
    path: '/dashboard/caficultor/sitios-web',
    roles: [ROLES.CAFICULTOR],
  },
  {
    id: 'caf_clima',
    label: 'Estado del tiempo',
    icon: 'cloud',
    path: '/dashboard/caficultor/estado-tiempo',
    roles: [ROLES.CAFICULTOR],
  },
  {
    id: 'caf_historico',
    label: 'Histórico',
    icon: 'calendar',
    path: '/dashboard/caficultor/historico',
    roles: [ROLES.CAFICULTOR],
  },
  {
    id: 'caf_estadisticas',
    label: 'Estadísticas',
    icon: 'bar-chart-2',
    path: '/dashboard/caficultor/estadisticas',
    roles: [ROLES.CAFICULTOR],
  },
  {
    id: 'caf_comunicaciones',
    label: 'Comunicaciones',
    icon: 'bell',
    path: '/dashboard/caficultor/comunicaciones',
    roles: [ROLES.CAFICULTOR],
  },
  {
    id: 'caf_educacion',
    label: 'Educación',
    icon: 'book-open',
    path: '/dashboard/caficultor/educacion',
    roles: [ROLES.CAFICULTOR],
  },
  {
    id: 'caf_archivos',
    label: 'Archivos',
    icon: 'file-text',
    path: '/dashboard/caficultor/archivos',
    roles: [ROLES.CAFICULTOR],
  },
];
